# Generated by Django 4.0.3 on 2022-09-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('damage', models.IntegerField(default=0)),
                ('upgrade_resource', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_cell', to='cell.cell')),
                ('next', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_cell', to='cell.cell')),
            ],
        ),
    ]
